- hosts: all
  tasks:
  - name: Adding Repo 
    yum_repository:
           description: Docker Setup 
           name: Docker
           baseurl:  https://download.docker.com/linux/centos/7/x86_64/stable             
           gpgcheck: no
    register: x       
    
  - debug:
           var : x 

  - package:
           name: "docker-ce-18.09.1-3.el7.x86_64"
           state: present
    register: y
    
  - debug:
           var: y

  - name: Starting docker service
    service:
           name: "docker"
           state: started
           enabled: yes
           #  register: z

           #  - debug: 
           #  var: z
  
  - command: pip3 install docker

  - name: Create directory
    file:
          path: /workspace
          state: directory

  - name: Copying the webpages to the directory
    copy: 
          src: sanket.html
          dest: /workspace
    register: a

  - debug: 
          var: a

  - name: Creating the container & exposed the port
    docker_container:
          name: WEBSERVER
          image: httpd
          state: started
          exposed_ports:
          - 80
          ports: 
          - 8081:80
          volumes:
          - /workspace:/usr/local/apache2/htdocs
            #  register: b
        
    # - debug:
          #  var: b          
